version: "3.8"
services:
  web:
    build: ./web
    volumes:
      - type: bind
        source: ./web
        target: /app
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      mainnet: {}
  testws:
    image: ksdn117/web-socket-test
    ports:
      - 8081:8010
    networks:
      mainnet: {}
networks:
  mainnet: