version: "3.8"
services:
  web-prod:
    build:
     context: ./web
     dockerfile: ProdDockerfile
    ports:
      - 1337:80
    networks:
      mainnet: {}
    depends_on:
      - simulator-prod
  simulator-prod:
    build: ./simulator
    ports:
      - 8081:8081
    environment:
      - FPS=2
    networks:
      mainnet: {}
networks:
  mainnet: