version: "3.8"
services:
  web:
    build: ./web
    volumes:
      - type: bind
        source: ./web/src
        target: /app/src
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      mainnet: {}
    depends_on:
      - simulator
  # testws:
  #   image: ksdn117/web-socket-test
  #   ports:
  #     - 8081:8010
  #   networks:
  #     mainnet: {}
  simulator:
    build: ./simulator
    ports:
      - 8081:8081
    environment:
      - FPS=2
    networks:
      mainnet: {}
networks:
  mainnet: