version: "3.8"
services:
  parser:
    build: .
    environment:
      - OBJECT_COLORS=248,206,204 restaurant;218,232,252 shop;213,232,212 general;225,213,231 services;204,204,204 route;245,245,245 checkin;204,0,204 toilets nofill;153,255,255 info;0,76,153 rest-space nofill
      - SMALL_ITEMS=221,221,221 lines;0,0,0 planes nofill 170000 200000
    volumes:
      - type: bind
        source: ./in
        target: /in
      - type: bind
        source: ./out
        target: /out
    command: python parse_image.py